# ============================================================
# application-DEV.yml — 开发环境
# 激活方式: set APP_ENV=DEV 或系统变量 APP_ENV=DEV
# ============================================================
app:
  http-port: 8881

db:
  host: 192.168.60.134
  port: 5432
  database: vertx
  user: postgres
  password: 123456
  pool-size: 10
  ssl: false

# DEV 环境 Keycloak 配置
auth:
  enabled: true
  realm: myrealm
  auth-server-url: http://192.168.60.134:8180
  client-id: vertx-app
  audience: vertx-app
  public-client: true
  default-roles: user
